version: "3.9"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    hostname: etcd-00
    command:
      - etcd
      - --name=etcd-00
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-00:2379,http://localhost:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-00:2380,http://localhost:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster-1
  sonya_server-1:
    hostname: sonya-1
    build:
      context: .
      dockerfile: sonya/Dockerfile
    environment:
      - RUST_LOG=info
      - QUEUE_DEFAULT=test
      - SERVICE_DISCOVERY_TYPE=ETCD
      - SERVICE_DISCOVERY_HOSTS=http://etcd-00:2379
      - SERVICE_DISCOVERY_INSTANCE_ADDR=http://sonya-1:8080
      - SECURE_SERVICE_TOKEN=dasdsadfaafwfwafwe
      - SECURE_JWT_EXPIRATION_TIME=315569520
    depends_on:
      - etcd
  sonya_server-2:
    hostname: sonya-2
    build:
      context: .
      dockerfile: sonya/Dockerfile
    environment:
      - RUST_LOG=info
      - QUEUE_DEFAULT=test
      - SERVICE_DISCOVERY_TYPE=ETCD
      - SERVICE_DISCOVERY_HOSTS=http://etcd-00:2379
      - SERVICE_DISCOVERY_INSTANCE_ADDR=http://sonya-2:8080
      - SECURE_SERVICE_TOKEN=dasdsadfaafwfwafwe
      - SECURE_JWT_EXPIRATION_TIME=315569520
    depends_on:
      - etcd
  sonya_proxy:
    build:
      context: .
      dockerfile: sonya-proxy/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=full
      - SERVICE_DISCOVERY_TYPE=ETCD
      - SERVICE_DISCOVERY_HOSTS=http://etcd-00:2379
      - SECURE_SERVICE_TOKEN=dasdsadfaafwfwafwe
      - SECURE_JWT_EXPIRATION_TIME=315569520
#      - SERVICE_DISCOVERY_DEFAULT_SHARDS=http://sonya-1:8080;http://sonya-2:8080
    depends_on:
      - etcd